# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_cards',
                'doc_host': 'https://zardarATgojitech.github.io',
                'git_url': 'https://github.com/zardarATgojitech/nbdev_cards',
                'lib_path': 'nbdev_cards'},
  'syms': { 'nbdev_cards.card': { 'nbdev_cards.card.Card': ('cards.html#card', 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card.__eq__': ('cards.html#card.__eq__', 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card.__gt__': ('cards.html#card.__gt__', 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card.__init__': ('cards.html#card.__init__', 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card.__lt__': ('cards.html#card.__lt__', 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card.__str__': ('cards.html#card.__str__', 'nbdev_cards/card.py')},
            'nbdev_cards.deck': { 'nbdev_cards.deck.Deck': ('deck.html#deck', 'nbdev_cards/deck.py'),
                                  'nbdev_cards.deck.Deck.__init__': ('deck.html#deck.__init__', 'nbdev_cards/deck.py'),
                                  'nbdev_cards.deck.Deck.__str__': ('deck.html#deck.__str__', 'nbdev_cards/deck.py')}}}
